@Offering_HostAddress = http://localhost:5084

# These routes are mapped only in the Development environment.
GET {{Offering_HostAddress}}/health
Accept: application/json

###

GET {{Offering_HostAddress}}/alive
Accept: application/json

###

GET {{Offering_HostAddress}}/openapi/v1.json
Accept: application/json

###
